'use client';

import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Inter as FontSans } from "next/font/google"

import { SessionProvider } from 'next-auth/react';
import { CartProvider } from '@/context/cartContext';
import Navbar from "@/components/ui/Navbar";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})

const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <CartProvider>
            <SessionProvider>
                <html lang="en">
                    <body className={cn(
                        "min-h-screen bg-background font-sans antialiased",
                        fontSans.variable
                    )}
                    >
                        <header>
                            <Navbar />
                        </header>
                        <main>{children} </main>
                    </body>

                    </html>
            </SessionProvider>
        </CartProvider>
    );
}
