import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils"
import { Inter as FontSans } from "next/font/google"
import Navbar from "@/app/components/Navbar";


const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

<<<<<<< Updated upstream
        <body className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
        )}
        >
            <header>
                <Navbar />
            </header>
            <main>{children} </main>
            </body>
=======
      <body className={cn(
        "min-h-screen  font-sans antialiased",
        fontSans.variable
      )}
      >
        <header>
          <Navbar />
        </header>
        <main>
           {children}
        </main>
        </body>
>>>>>>> Stashed changes
    </html>
  );
}
